import os
import sys
import time
import csv
import json
import gc

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

import cv2
import numpy as np
import open3d as o3d

from colmap_loader import load_colmap_model
from mesh_generator import generate_mesh

print("[RECONSTRUCTION] COLMAP result processing module loaded")


# =========================================================
# LOAD IMAGE
# =========================================================

def process_single_image(image_info):
    """
    image_info must contain:
        {
            "path": "...",
            "name": "image_001.JPG"
        }

    IMPORTANT:
    Do NOT rotate images here.
    COLMAP poses/intrinsics correspond to the original image orientation.
    """

    path = image_info["path"]
    name = image_info["name"]

# Read image
    img = cv2.imread(
        path,
        cv2.IMREAD_COLOR
    )

    if img is None:
        print(f"[WARNING] Failed to load image: {path}")
        return None

    # -------------------------------------------------
    # MEMORY OPTIMIZATION
    # -------------------------------------------------
    # Large DSLR/mobile images consume huge amounts
    # of RAM. Downscale them before any processing.
    # COLMAP has already estimated the poses, so
    # moderate resizing will not affect pose loading.
    # -------------------------------------------------

    MAX_IMAGE_WIDTH = 2000

    h, w = img.shape[:2]

    if w > MAX_IMAGE_WIDTH:

        scale = MAX_IMAGE_WIDTH / float(w)

        new_w = int(w * scale)
        new_h = int(h * scale)

        img = cv2.resize(
            img,
            (new_w, new_h),
            interpolation=cv2.INTER_AREA
        )

    print(
        f"[IMAGE] {name}: "
        f"{w}x{h}  -->  "
        f"{img.shape[1]}x{img.shape[0]}"
    )

    return {
        "image": img,
        "name": name,
        "path": path
    }


# =========================================================
# SAVE POINT CLOUD
# =========================================================

def save_point_cloud(points, colors, output_path):

    os.makedirs(
        os.path.dirname(output_path),
        exist_ok=True
    )

    pcd = o3d.geometry.PointCloud()

    pcd.points = o3d.utility.Vector3dVector(
        np.asarray(points, dtype=np.float64)
    )

    pcd.colors = o3d.utility.Vector3dVector(
        np.asarray(colors, dtype=np.float64)
    )

    success = o3d.io.write_point_cloud(
        output_path,
        pcd
    )

    if not success:
        raise RuntimeError(
            f"Failed to save point cloud: {output_path}"
        )

    return output_path


# =========================================================
# ANALYTICS
# =========================================================

def build_analytics(
    sparse_points,
    dense_points,
    camera_positions,
    processing_time,
    total_input_images,
    registered_images
):

    total_points = (
        len(sparse_points)
        + len(dense_points)
    )

    registration_ratio = (
        len(registered_images)
        / max(total_input_images, 1)
    )

    # Temporary audit metric.
    # We will replace this with proper quality metrics
    # during the analytics stage.
    health_score = round(
        registration_ratio * 100.0,
        2
    )

    return {

        "total_sparse_points":
            int(len(sparse_points)),

        "total_dense_points":
            int(len(dense_points)),

        "total_points":
            int(total_points),

        "total_cameras":
            int(len(camera_positions)),

        "total_input_images":
            int(total_input_images),

        "registered_images":
            int(len(registered_images)),

        "registration_ratio":
            round(registration_ratio * 100.0, 2),

        "processing_time":
            round(processing_time, 2),

        # Temporary placeholders.
        # Stage 5 will replace these.
        "successful_pairs":
            0,

        "failed_pairs":
            0,

        "avg_confidence":
            0.0,

        "avg_inliers":
            0,

        "avg_points":
            int(total_points),

        "health_score":
            health_score
    }


# =========================================================
# MAIN
# =========================================================

def run_reconstruction(
    uploaded_files,
    dense_ply_path,
    progress_callback=print,
    config=None
):
    config = config or {}
    """
    Process the COLMAP reconstruction results.

    Objective
    ---------
    Consume the dense point cloud generated by COLMAP,
    clean it, generate a mesh, and produce analytics
    for the PowerTwinAI application.

    Parameters
    ----------
    uploaded_files : list[dict]
        Prepared image information produced by the
        preprocessing stage.

    dense_ply_path : str
        Path to COLMAP's fused dense point cloud.

    progress_callback : callable
        Logging callback used by the reconstruction runner.

    Returns
    -------
    tuple
        Final points, colors, camera positions,
        match visuals, PLY path, pair logs,
        processing time, and analytics.
    """

    start_time = time.time()

    progress_callback(
        "[RECONSTRUCTION] Processing COLMAP results..."
    )

    # =====================================================
    # INPUT VALIDATION
    # =====================================================

    if not dense_ply_path:

        raise ValueError(
            "COLMAP dense point-cloud path was not provided."
        )

    if not os.path.exists(dense_ply_path):

        raise FileNotFoundError(
            "COLMAP dense point cloud not found: "
            f"{dense_ply_path}"
        )

    # =====================================================
    # INPUT IMAGE COUNT
    # =====================================================

    total_input_images = len(
        uploaded_files
    )

    progress_callback(
        f"[RECONSTRUCTION] Input images: "
        f"{total_input_images}"
    )

    # =====================================================
    # LOAD COLMAP SPARSE MODEL
    # =====================================================

    progress_callback(
        "[COLMAP] Loading sparse reconstruction..."
    )

    (
        cameras,
        registered_images,
        _camera_positions,
        sparse_points,
        sparse_colors
    ) = load_colmap_model(
        "colmap_data"
    )

    progress_callback(
        f"[COLMAP] Registered Images: "
        f"{len(registered_images)}"
    )

    progress_callback(
        f"[COLMAP] Sparse Points: "
        f"{len(sparse_points)}"
    )

    # =====================================================
    # CAMERA POSITIONS
    # =====================================================

    camera_positions = []

    for image_name, pose in registered_images.items():

        camera_positions.append(
            pose["camera_center"]
        )

    camera_positions = np.asarray(
        camera_positions,
        dtype=np.float64
    )

    # =====================================================
    # LOAD COLMAP DENSE POINT CLOUD
    # =====================================================

    from mesh_generator import is_mesh_ply

    if is_mesh_ply(dense_ply_path):
        progress_callback(
            "[INPUT CHECK] Input file is verified as a 3D surface mesh with triangular faces."
        )
    else:
        progress_callback(
            "[INPUT CHECK] Input file is a 3D point cloud (vertices only, no face elements). "
            "Pipeline will perform normal estimation & Poisson surface meshing."
        )

    progress_callback(
        "[COLMAP-DENSE] Loading fused dense point cloud..."
    )

    dense_pcd = o3d.io.read_point_cloud(
        dense_ply_path
    )

    if dense_pcd.is_empty():

        raise RuntimeError(
            "COLMAP fused point cloud is empty."
        )

    dense_points = np.asarray(
        dense_pcd.points,
        dtype=np.float64
    )

    # =====================================================
    # DENSE COLORS
    # =====================================================

    if dense_pcd.has_colors():

        dense_colors = np.asarray(
            dense_pcd.colors,
            dtype=np.float64
        )

    else:

        progress_callback(
            "[WARNING] Dense point cloud has no colors."
        )

        dense_colors = np.ones(
            (len(dense_points), 3),
            dtype=np.float64
        )

    progress_callback(
        f"[COLMAP-DENSE] Dense Points: "
        f"{len(dense_points):,}"
    )

    # =====================================================
    # REMOVE INVALID VALUES
    # =====================================================

    finite_mask = (
        np.all(
            np.isfinite(dense_points),
            axis=1
        )
        &
        np.all(
            np.isfinite(dense_colors),
            axis=1
        )
    )

    dense_points = dense_points[
        finite_mask
    ]

    dense_colors = dense_colors[
        finite_mask
    ]

    if len(dense_points) == 0:

        raise RuntimeError(
            "All COLMAP dense points were invalid."
        )

    # Keep colors valid for Open3D.
    dense_colors = np.clip(
        dense_colors,
        0.0,
        1.0
    )

    # =====================================================
    # CLEAN DENSE POINT CLOUD
    # =====================================================

    progress_callback(
        "[CLEANING] Cleaning COLMAP dense point cloud..."
    )

    pcd = o3d.geometry.PointCloud()

    pcd.points = (
        o3d.utility.Vector3dVector(
            dense_points
        )
    )

    pcd.colors = (
        o3d.utility.Vector3dVector(
            dense_colors
        )
    )

    # =====================================================
    # STATISTICAL OUTLIER REMOVAL
    # =====================================================

    raw_dense_points_count = len(dense_points)
    progress_callback(f"[CLEANING] Raw dense points: {raw_dense_points_count:,}")

    # =====================================================
    # STAGE 1 — STATISTICAL OUTLIER REMOVAL
    # =====================================================
    outlier_std = float(config.get("outlier_std_ratio", 1.8))
    outlier_k = int(config.get("outlier_nb_neighbors", 25))

    if len(dense_points) >= outlier_k:
        try:
            pcd, _ = pcd.remove_statistical_outlier(
                nb_neighbors=outlier_k,
                std_ratio=outlier_std
            )
            progress_callback(
                f"[CLEANING] After statistical filter (k={outlier_k}, std={outlier_std}): "
                f"{len(np.asarray(pcd.points)):,} points"
            )
        except Exception as e:
            print(f"[WARNING] Statistical outlier removal failed: {e}")

    # =====================================================
    # STAGE 2 — RADIUS OUTLIER REMOVAL (Floating blob removal)
    # =====================================================
    if len(np.asarray(pcd.points)) >= 50:
        try:
            pts = np.asarray(pcd.points)
            extent = np.max(pts, axis=0) - np.min(pts, axis=0)
            radius = float(np.mean(extent)) * 0.025

            pcd, _ = pcd.remove_radius_outlier(
                nb_points=8,
                radius=max(radius, 1e-4)
            )
            progress_callback(
                f"[CLEANING] After radius filter: "
                f"{len(np.asarray(pcd.points)):,} points"
            )
        except Exception as e:
            print(f"[WARNING] Radius outlier removal failed: {e}")

    # =====================================================
    # STAGE 3 — VOXEL DOWNSAMPLING (OPTIONAL ONLY)
    # In High Density / Standard mode, voxel downsampling is DISABLED
    # to preserve all genuinely reconstructed multi-view points.
    # =====================================================
    if config.get("apply_voxel_downsampling", False) and len(np.asarray(pcd.points)) >= 100:
        try:
            pts = np.asarray(pcd.points)
            extent = np.max(pts, axis=0) - np.min(pts, axis=0)
            voxel_size = float(np.mean(extent)) * 0.003
            pcd = pcd.voxel_down_sample(voxel_size=max(voxel_size, 1e-5))
            progress_callback(
                f"[CLEANING] After voxel downsample: {len(np.asarray(pcd.points)):,} points"
            )
        except Exception as e:
            print(f"[WARNING] Voxel downsampling failed: {e}")

    # =====================================================
    # STAGE 4 — NORMAL ESTIMATION & ORIENTATION
    # =====================================================
    if len(np.asarray(pcd.points)) >= 20:
        try:
            progress_callback("[CLEANING] Estimating normals and establishing tangent plane orientation...")
            dists = pcd.compute_nearest_neighbor_distance()
            avg_d = float(np.median(dists)) if len(dists) > 0 else 0.05
            pcd.estimate_normals(
                search_param=o3d.geometry.KDTreeSearchParamHybrid(
                    radius=max(avg_d * 3.5, 0.02),
                    max_nn=40
                )
            )
            try:
                pcd.orient_normals_consistent_tangent_plane(k=min(25, max(10, len(pcd.points) // 20)))
            except Exception:
                pass
            pcd.normalize_normals()
            progress_callback("[CLEANING] Normals successfully oriented.")
        except Exception as e:
            print(f"[WARNING] Normal estimation warning: {e}")

    # =====================================================
    # STAGE 5 — HOLE & COVERAGE ANALYSIS (Requirement 5)
    # =====================================================
    coverage_info = {}
    try:
        from core.coverage_analyzer import analyze_point_cloud_coverage
        coverage_info = analyze_point_cloud_coverage(pcd)
        if coverage_info.get("has_coverage_warning"):
            progress_callback(f"[COVERAGE WARNING] {coverage_info.get('warning_message')}")
        else:
            progress_callback(f"[COVERAGE] Completeness score: {coverage_info.get('coverage_score')}% (no critical gaps detected)")
    except Exception as e:
        print(f"[WARNING] Coverage analysis warning: {e}")

    final_points = np.asarray(
        pcd.points,
        dtype=np.float64
    )

    final_colors = np.asarray(
        pcd.colors,
        dtype=np.float64
    )

    if len(final_points) == 0:

        raise RuntimeError(
            "Point-cloud cleaning removed all points."
        )

    progress_callback(
        f"[CLEANING] Final Points: "
        f"{len(final_points):,}"
    )

    # =====================================================
    # OUTPUT DIRECTORY
    # =====================================================

    os.makedirs(
        "output",
        exist_ok=True
    )

    # =====================================================
    # SAVE FINAL POINT CLOUD (Structured & Legacy outputs)
    # =====================================================

    ply_path = save_point_cloud(
        final_points,
        final_colors,
        os.path.join("output", "reconstruction.ply")
    )
    # Also save to outputs/dense/filtered_pointcloud.ply (Requirement 13)
    structured_filtered_dest = os.path.join("outputs", "dense", "filtered_pointcloud.ply")
    os.makedirs(os.path.dirname(structured_filtered_dest), exist_ok=True)
    save_point_cloud(final_points, final_colors, structured_filtered_dest)

    progress_callback(
        f"[OUTPUT] Filtered Point Cloud Saved: {ply_path} and {structured_filtered_dest}"
    )

    # =====================================================
    # MESH GENERATION (Poisson / Ball Pivoting)
    # =====================================================

    meshing_method = config.get("meshing_method", "Poisson")
    poisson_depth = int(config.get("poisson_depth", 8))
    density_trim = float(config.get("mesh_density_trim", 0.10))
    remove_floating = bool(config.get("remove_floating_components", True))

    progress_callback(f"[MESH] Generating Surface Mesh via {meshing_method} (depth={poisson_depth})...")

    try:
        mesh_result = generate_mesh(
            final_points,
            final_colors,
            output_dir="output",
            output_name="mesh",
            method=meshing_method,
            poisson_depth=poisson_depth,
            density_quantile=density_trim,
            outlier_std_ratio=outlier_std,
            remove_floating_components=remove_floating,
            pcd_distance_trim=True,
            seal_holes=True,
            ml_complete_blind_spots=bool(config.get("ml_complete_blind_spots", False)),
            progress_callback=progress_callback
        )

        gc.collect()

        if mesh_result is not None:

            progress_callback(
                f"[MESH] Vertices: "
                f"{mesh_result['vertices']:,}"
            )

            progress_callback(
                f"[MESH] Triangles: "
                f"{mesh_result['triangles']:,}"
            )

    except Exception as e:

        print(
            f"[WARNING] Mesh generation failed: {e}"
        )

        mesh_result = None

    # =====================================================
    # PAIR LOGS
    # =====================================================

    # =====================================================
    # PAIR LOGS — derived from COLMAP sparse model
    # =====================================================
    # The UI expects a CSV with columns:
    #   pair, status, confidence, inliers, points
    #
    # We build one row per image using data already loaded
    # from the COLMAP sparse model:
    #   - registered images → status=registered
    #   - unregistered images → status=failed
    #   - confidence = normalised track length (0–1)
    #   - inliers = points visible in this image
    #   - points = same (sparse 3D points observed)
    # =====================================================

    pair_logs = []

    pair_log_path = os.path.join("output", "pair_logs.csv")

    # Build a per-image visibility count from points3D.txt
    # Each 3D point records which image IDs observe it.
    image_point_count = {}  # image_name -> int

    for img_name in registered_images:
        image_point_count[img_name] = 0

    # Count how many sparse points each registered image sees
    # We use the colmap points2D data embedded in images.txt
    # (already parsed into registered_images via colmap_loader).
    # Fallback: count from sparse_points length per image.
    # Best proxy available without re-parsing the DB:
    # distribute sparse_points evenly as a lower bound.
    total_sparse = max(len(sparse_points), 1)

    # Read images.txt POINTS2D lines to get exact per-image counts
    images_txt = os.path.join("colmap_data", "images.txt")
    try:
        with open(images_txt, "r", encoding="utf-8") as fh:
            lines_txt = fh.readlines()

        i = 0
        while i < len(lines_txt):
            line = lines_txt[i].strip()
            if not line or line.startswith("#"):
                i += 1
                continue
            parts = line.split()
            if len(parts) >= 10:
                # This is a pose line — next line is POINTS2D
                img_name = " ".join(parts[9:])
                i += 1
                if i < len(lines_txt):
                    pts2d_line = lines_txt[i].strip()
                    # Each point2D entry: X Y POINT3D_ID
                    # Count entries with POINT3D_ID != -1
                    pts2d_parts = pts2d_line.split()
                    visible = sum(
                        1 for k in range(2, len(pts2d_parts), 3)
                        if pts2d_parts[k] != "-1"
                    )
                    image_point_count[img_name] = visible
            i += 1
    except Exception as e:
        progress_callback(f"[PAIR LOGS] Could not read points2D: {e}")

    # Compute max for normalisation
    max_pts = max(image_point_count.values(), default=1) if image_point_count else 1

    # All uploaded filenames (stems only, to match COLMAP jpg names)
    all_image_names = {
        f["name"] for f in uploaded_files
    }

    with open(pair_log_path, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["pair", "status", "confidence", "inliers", "points"])

        # Registered images
        for img_name, pose in registered_images.items():
            pts_count = image_point_count.get(img_name, 0)
            confidence = round(pts_count / max_pts, 4) if max_pts > 0 else 0.0
            writer.writerow([
                img_name,
                "registered",
                confidence,
                pts_count,
                pts_count,
            ])
            pair_logs.append({
                "pair": img_name,
                "status": "registered",
                "confidence": confidence,
                "inliers": pts_count,
                "points": pts_count,
            })

        # Unregistered images (uploaded but not in sparse model)
        registered_names = set(registered_images.keys())
        for img_name in all_image_names:
            # COLMAP converts to .jpg stems — match both
            stem = os.path.splitext(img_name)[0]
            jpg_name = stem + ".jpg"
            if img_name not in registered_names and jpg_name not in registered_names:
                writer.writerow([img_name, "failed", 0.0, 0, 0])
                pair_logs.append({
                    "pair": img_name,
                    "status": "failed",
                    "confidence": 0.0,
                    "inliers": 0,
                    "points": 0,
                })

    progress_callback(
        f"[PAIR LOGS] Written {len(pair_logs)} rows -> {pair_log_path}"
    )

    # =====================================================
    # ANALYTICS
    # =====================================================

    processing_time = (
        time.time() - start_time
    )

    analytics = build_analytics(
        sparse_points,
        final_points,
        camera_positions,
        processing_time,
        total_input_images,
        registered_images
    )

    from core.gpu_detector import get_gpu_info
    gpu_info = get_gpu_info()

    retention_pct = round((len(final_points) / max(raw_dense_points_count, 1)) * 100.0, 1)
    analytics["raw_dense_points"] = int(raw_dense_points_count)
    analytics["filtered_points"] = len(final_points)
    analytics["retention_ratio"] = retention_pct
    analytics["coverage_score"] = coverage_info.get("coverage_score", 0.0)
    analytics["has_coverage_warning"] = coverage_info.get("has_coverage_warning", False)
    analytics["coverage_warning"] = coverage_info.get("warning_message", None)
    analytics["coverage_info"] = coverage_info
    analytics["gpu_info"] = gpu_info
    analytics["config"] = config
    analytics["reconstruction_mode"] = config.get("name", "Standard")

    # Load ML Pair Selection Telemetry if present
    ml_telemetry_file = os.path.join("output", "ml_pair_telemetry.json")
    if not os.path.exists(ml_telemetry_file):
        ml_telemetry_file = os.path.join("temp_session", "ml_pair_telemetry.json")
    if os.path.exists(ml_telemetry_file):
        try:
            with open(ml_telemetry_file, "r", encoding="utf-8") as tf:
                analytics["ml_pair_telemetry"] = json.load(tf)
        except Exception:
            pass

    # 20-Metric Diagnostic Analysis Report
    try:
        from core.reconstruction_diagnostics import generate_diagnostics_report
        diagnostics = generate_diagnostics_report(
            colmap_dir="colmap_data",
            colmap_workspace="colmap_workspace",
            output_dir="output",
            mesh_path=os.path.join("output", "mesh.ply"),
            pointcloud_path=os.path.join("output", "reconstruction.ply"),
            total_input_images=total_input_images
        )
        analytics["diagnostics"] = diagnostics
        progress_callback(
            f"[DIAGNOSTICS] 20-Metric Diagnostic Report Generated: {diagnostics['mesh_vertices']:,} verts, "
            f"{diagnostics['mesh_faces']:,} faces, {diagnostics['boundary_edges']} boundary edges, "
            f"{diagnostics['num_detected_holes']} holes."
        )
    except Exception as e:
        print(f"[WARNING] Diagnostics generation error: {e}")

    # Neuralangelo Dataset Preparation (Requirement 12 & 13)
    try:
        from backends.neuralangelo_backend import prepare_neuralangelo_dataset
        na_prep = prepare_neuralangelo_dataset(
            images_dir=os.path.join("colmap_workspace", "images"),
            colmap_data_dir="colmap_data",
            output_dir=os.path.join("outputs", "neuralangelo")
        )
        analytics["neuralangelo_ready"] = True
        progress_callback(f"[NEURALANGELO] Dataset exported ({na_prep['num_frames']} frames) to outputs/neuralangelo")
    except Exception as e:
        analytics["neuralangelo_ready"] = False
        print(f"[NEURALANGELO] Preparation note: {e}")

    if mesh_result is not None:
        analytics["mesh_path"] = str(mesh_result.get("ply", ""))
        analytics["mesh_obj_path"] = str(mesh_result.get("obj", ""))
        analytics["mesh_vertices"] = int(mesh_result.get("vertices", 0))
        analytics["mesh_triangles"] = int(mesh_result.get("triangles", 0))
        analytics["has_faces"] = bool(mesh_result.get("has_faces", False))

    # =====================================================
    # RESULT DATA
    # =====================================================

    match_visuals = []

    progress_callback(
        "[RECONSTRUCTION] COLMAP result processing complete."
    )

    progress_callback(
        f"[INFO] Final Points: "
        f"{len(final_points):,}"
    )

    progress_callback(
        f"[INFO] Registered Cameras: "
        f"{len(camera_positions)}"
    )

    progress_callback(
        f"[INFO] Processing Time: "
        f"{processing_time:.2f} sec"
    )

    return (
        final_points,
        final_colors,
        camera_positions,
        match_visuals,
        ply_path,
        pair_logs,
        processing_time,
        analytics
    )